/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InputType = ("TEXT" | "EMAIL" | "PASSWORD" | "NUMBER")
export type ButtonVariant = "PRIMARY" | "SECONDARY" | "DANGER";
export type TextType = "RAW" | "MARKDOWN";
export type LayoutGridVariant = "GRID2" | "GRID4";
export type LayoutJustifyContent = "NORMAL" | "END";
export type LayoutType = "GRID" | "FLEX";

export interface Form {
  $schema: string;
  id: string;
  config: FormConfig;
  components: Component[];
}
export interface FormConfig {
  renderer: string;
  theme: string;
}
export interface Component {
  id: string;
  type: "Button" | "Input" | "Layout" | "Link" | "Text";
  config: Input | Link | Button | Text | Layout;
}
export interface Input {
  label: string;
  required: boolean;
  type: InputType;
  value: string;
}
export interface Link {
  href: string;
  name: string;
}
export interface Button {
  action: string;
  icon: string;
  name: string;
  variant: ButtonVariant;
}
export interface Text {
  content: string;
  type: TextType;
}
export interface Layout {
  components: Component[];
  gridVariant: LayoutGridVariant;
  justifyContent: LayoutJustifyContent;
  type: LayoutType;
}
