/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Renderer = "JSF"
export type ButtonVariant = "PRIMARY" | "SECONDARY" | "DANGER";
export type InputType = "TEXT" | "EMAIL" | "PASSWORD";
export type TextType = "RAW" | "MARKDOWN";

export interface Form {
  $schema: string;
  id: string;
  config: FormConfig;
  components: Component[];
}
export interface FormConfig {
  renderer: Renderer;
  theme: string;
}
export interface Component {
  id: string;
  type: "Button" | "Input" | "Layout" | "Link" | "Text";
  config: Layout | Button | Input | Link | Text;
}
export interface Layout {
  components: Component[];
}
export interface Button {
  action: string;
  icon: string;
  name: string;
  variant: ButtonVariant;
}
export interface Input {
  label: string;
  required: boolean;
  type: InputType;
  value: string;
}
export interface Link {
  href: string;
  name: string;
}
export interface Text {
  content: string;
  type: TextType;
}
