/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ButtonVariant = ("PRIMARY" | "SECONDARY" | "DANGER")
export type InputType = 'TEXT' | 'EMAIL' | 'PASSWORD' | 'NUMBER';
export type LayoutGridVariant = 'GRID2' | 'GRID4' | 'FREE';
export type LayoutJustifyContent = 'NORMAL' | 'END';
export type LayoutType = 'GRID' | 'FLEX';
export type OrientationType = 'horizontal' | 'vertical';
export type TextType = 'RAW' | 'MARKDOWN';

export interface Form {
  $schema: string;
  id: string;
  config: FormConfig;
  components: Component[];
}
export interface FormConfig {
  renderer: string;
  theme: string;
}
export interface Component {
  id: string;
  type:
    | 'Button'
    | 'Checkbox'
    | 'Combobox'
    | 'DataTable'
    | 'DataTableColumn'
    | 'DatePicker'
    | 'Input'
    | 'Layout'
    | 'Link'
    | 'Radio'
    | 'Select'
    | 'Text'
    | 'Textarea'
    | 'Fieldset';
  config:
    | Button
    | Checkbox
    | Combobox
    | DataTable
    | DataTableColumn
    | DatePicker
    | Input
    | Layout
    | Link
    | Radio
    | Select
    | Text
    | Textarea
    | Fieldset;
}
export interface Button {
  action: string;
  icon: string;
  lgSpan: string;
  mdSpan: string;
  name: string;
  variant: ButtonVariant;
}
export interface Checkbox {
  label: string;
  lgSpan: string;
  mdSpan: string;
  selected: string;
}
export interface Combobox {
  completeMethod: string;
  itemLabel: string;
  itemValue: string;
  label: string;
  lgSpan: string;
  mdSpan: string;
  value: string;
  withDropdown: boolean;
}
export interface DataTable {
  components: Component[];
  label: string;
  lgSpan: string;
  mdSpan: string;
  value: string;
}
export interface DataTableColumn {
  header: string;
  lgSpan: string;
  mdSpan: string;
  value: string;
}
export interface DatePicker {
  datePattern: string;
  label: string;
  lgSpan: string;
  mdSpan: string;
  showTime: boolean;
  timePattern: string;
  value: string;
}
export interface Input {
  label: string;
  lgSpan: string;
  mdSpan: string;
  required: boolean;
  type: InputType;
  value: string;
}
export interface Layout {
  components: Component[];
  gridVariant: LayoutGridVariant;
  justifyContent: LayoutJustifyContent;
  lgSpan: string;
  mdSpan: string;
  type: LayoutType;
}
export interface Link {
  href: string;
  lgSpan: string;
  mdSpan: string;
  name: string;
}
export interface Radio {
  dynamicItemsLabel: string;
  dynamicItemsList: string;
  dynamicItemsValue: string;
  label: string;
  lgSpan: string;
  mdSpan: string;
  orientation: OrientationType;
  staticItems: SelectItem[];
  value: string;
}
export interface SelectItem {
  label: string;
  value: string;
}
export interface Select {
  dynamicItemsLabel: string;
  dynamicItemsList: string;
  dynamicItemsValue: string;
  label: string;
  lgSpan: string;
  mdSpan: string;
  staticItems: SelectItem[];
  value: string;
}
export interface Text {
  content: string;
  lgSpan: string;
  mdSpan: string;
  type: TextType;
}
export interface Textarea {
  autoResize: boolean;
  label: string;
  lgSpan: string;
  mdSpan: string;
  rows: string;
  value: string;
}
export interface Fieldset {
  components: Component[];
  legend: string;
  disabled: boolean;
  collapsible: boolean;
  collapsed: boolean;
  lgSpan: string;
  mdSpan: string;
}
